# Generated by Django 5.1 on 2025-04-15 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.FileField(upload_to=''),
        ),
    ]
